name: Build and Push to ECR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'
      dockerfile:
        description: 'Dockerfile to use (e.g., Dockerfile or Dockerfile.aws.lambda)'
        required: true
        default: 'Dockerfile'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 841095141312.dkr.ecr.eu-west-1.amazonaws.com
  ECR_REPOSITORY: ml-models

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::841095141312:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          sudo docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          DOCKERFILE: ${{ github.event.inputs.dockerfile }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          echo "Building Docker image using $DOCKERFILE for $ENVIRONMENT environment with tag $IMAGE_TAG..."
          sudo docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
          
          # Also tag with environment
          sudo docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT

          echo "Pushing to ECR..."
          sudo docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          sudo docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT
          
          echo "Image pushed to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "Image also tagged as: $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT"
